backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
media_folder: public/assets/images
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: 'YYYY MM DD HH:mm:ss'}
      - {label: "Modified Date", name: "modified_date", widget: "datetime", format: 'YYYY MM DD HH:mm:ss'}
      - {label: "Body", name: "content", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", default: public/assets/images/posts}